export interface SignalTask {
  id: string
  text: string
}

export const SIGNAL_TASKS: SignalTask[] = [
  { id: 's1', text: 'Konuşurken sürekli gözlerini kaçır' },
  { id: 's2', text: 'Birine en az 2 kere omuz at / dokun' },
  { id: 's3', text: "Cümlelerinin sonuna 'yani' ekle" },
  { id: 's4', text: 'Birisine iltifat et ama abart' },
  { id: 's5', text: 'En az 3 kere su / içecek iç' },
  { id: 's6', text: 'Birinin sözünü kes' },
  { id: 's7', text: 'Sürekli gülümse ama sebepsiz' },
  { id: 's8', text: "Birine 'gerçekten mi?' diye sor" },
  { id: 's9', text: 'Konuşurken ellerinle saçını düzelt' },
  { id: 's10', text: 'Her cümleden sonra hafifçe öksür' },
  { id: 's11', text: 'Birine ismiyle hitap etmeye çalış' },
  { id: 's12', text: 'Konuşurken ayağını yere vur / salla' },
  { id: 's13', text: "Sık sık 'aslında' de" },
  { id: 's14', text: 'Birine yanlışlıkla yanlış isimle hitap et' },
  { id: 's15', text: 'Telefonuna bakıyormuş gibi yap (en az 2 kez)' },
  { id: 's16', text: 'Birine komik bir hikaye uydur' },
  { id: 's17', text: 'Sürekli etrafa bakın, dikkatin dağınık olsun' },
  { id: 's18', text: 'Birine sır vermiş gibi fısılda' },
  { id: 's19', text: 'Konuşurken kollarını bağla ve öyle kal' },
  { id: 's20', text: "En az 2 kere 'tamam mı?' diye sor" },
  { id: 's21', text: 'Birine abartılı şekilde hak ver' },
  { id: 's22', text: 'Kendi cümleni yarıda bırakıp başka konuya geç' },
  { id: 's23', text: 'Birine el salla veya selam ver (sebepsiz)' },
  { id: 's24', text: 'Konuşurken burnunu kaşı' },
  { id: 's25', text: 'En az 2 kere esnemeye çalış' },
  { id: 's26', text: "Cümlelerine 'kısaca' diye başla" },
  { id: 's27', text: 'Birine aynı soruyu farklı şekilde tekrar sor' },
  { id: 's28', text: 'Konuşurken bileğini veya saati kontrol et' },
  { id: 's29', text: 'Birinin söylediğini abartılı şekilde tekrar et' },
  { id: 's30', text: 'Sürekli hafifçe başını sallayarak dinle' },
  { id: 's31', text: "En az 3 kere 'ilginç' de" },
  { id: 's32', text: 'Birine sebepsiz teşekkür et' },
  { id: 's33', text: 'Konuşurken kalemini / bir nesneyi çevir' },
  { id: 's34', text: 'Birine yanlış bilgi verip hemen düzelt' },
  { id: 's35', text: 'Her fırsatta hava durumundan bahset' },
  { id: 's36', text: 'Birine göz kırp (en az 1 kez)' },
  { id: 's37', text: "Cümlelerinin arasına 'şey' ekle" },
  { id: 's38', text: 'Birine abartılı şekilde şaşır' },
  { id: 's39', text: 'Konuşurken sandalyende ileri geri sallan' },
  { id: 's40', text: 'Birine ismini unutmuş gibi davran' },
  { id: 's41', text: 'En az 2 kere kahkaha at (abartmadan)' },
  { id: 's42', text: "Sık sık 'anladın mı?' diye sor" },
  { id: 's43', text: 'Birine komplo teorisi gibi bir iddia at' },
  { id: 's44', text: 'Konuşurken parmaklarını şıklat' },
  { id: 's45', text: 'Birine sürekli haklı olduğunu hissettir' },
  { id: 's46', text: 'Her konuyu yemeğe / içeceğe bağla' },
  { id: 's47', text: 'Birine fısıldar gibi yaklaş ama normal konuş' },
  { id: 's48', text: "En az 2 kere 'yemin ederim' de" },
  { id: 's49', text: 'Konuşurken omuz silk' },
  { id: 's50', text: 'Birine geçmiş bir anıyı uydurup anlat' },
  { id: 's51', text: 'Sürekli birini onaylayan sesler çıkar (hı-hı, evet)' },
  { id: 's52', text: 'Birine yanlışlıkla İngilizce bir kelime karıştır' },
  { id: 's53', text: 'Konuşurken kaşlarını kaldırarak dinle' },
  { id: 's54', text: 'Birine "sen de mi öyle düşünüyorsun?" diye sor' },
]
