export interface SignalTask {
  id: string
  text: string
}

/**
 * Behavioral tasks for the secret Signaler.
 * Natural in group chat, observable, fun if noticed — not cartoonish tics.
 */
export const SIGNAL_TASKS: SignalTask[] = [
  { id: 's1', text: 'Cümlelerine sık sık "aslında" ile başla' },
  { id: 's2', text: 'Her fikrinin sonuna "bence" ekle' },
  { id: 's3', text: 'En az 3 kez "yani kısaca" de' },
  { id: 's4', text: 'Birine bir şeyi anlatırken abartılı detay ver' },
  { id: 's5', text: 'Konuşurken ara sıra kendi kendine gül' },
  { id: 's6', text: 'Birinin cümlesini bitirmeden "aynen" de' },
  { id: 's7', text: 'En az 2 kez "yeminle" veya "vallahi" kullan' },
  { id: 's8', text: 'Soru sorarken seçenek sun: "A mı B mi?"' },
  { id: 's9', text: 'Bir konuyu anlatırken yarıda bırakıp "sonra anlatırım" de' },
  { id: 's10', text: 'En az 2 kez birine ismiyle hitap et' },
  { id: 's11', text: 'Masadaki herkese en az bir soru sor' },
  { id: 's12', text: 'Birine samimi ama abartılı bir iltifat et' },
  { id: 's13', text: 'Birinin fikrine önce katıl, sonra nazikçe tersini savun' },
  { id: 's14', text: 'İki kişiyi aynı konuda karşı karşıya getir ("sen ne diyorsun?")' },
  { id: 's15', text: 'Birine "senin yerinde olsam..." diye tavsiye ver' },
  { id: 's16', text: 'Birine özel bir sır anlatıyormuş gibi yaklaş ve fısılda' },
  { id: 's17', text: 'Birini "haklısın aslında" diyerek abartılı onayla' },
  { id: 's18', text: 'Birine yanlış isimle hitap edip hemen düzelt' },
  { id: 's19', text: 'Birinin anlattığı hikayeye kendi uydurma bir detay ekle' },
  { id: 's20', text: 'Birine "bunu daha önce de konuşmuştuk" de (uydur)' },
  { id: 's21', text: 'Her konuyu bir yemek veya içeceğe bağla' },
  { id: 's22', text: 'En az bir kez çocukluk anısı uydurup anlat' },
  { id: 's23', text: 'Bir film veya dizi spoileri veriyormuş gibi yap (uydur)' },
  { id: 's24', text: 'Birine saçma ama ciddi bir "hayat tavsiyesi" ver' },
  { id: 's25', text: 'Konuyu en az 2 kez paraya / fiyata getir' },
  { id: 's26', text: 'Birine "bu bana birini hatırlattı" deyip uydurma kıyas yap' },
  { id: 's27', text: 'En az bir kez gelecek planından bahset (gerçek veya uydurma)' },
  { id: 's28', text: 'Birine "senin tarzın bambaşka" tarzı belirsiz bir yorum yap' },
  { id: 's29', text: 'Bir iddiayı "istatistiklere göre" diye uydurarak destekle' },
  { id: 's30', text: 'Birine "bunu kimse bilmiyor ama..." diye başla' },
  { id: 's31', text: 'Sıradan bir şeye abartılı şekilde şaşır' },
  { id: 's32', text: 'Birinin esprisine herkesten geç ve daha yüksek gül' },
  { id: 's33', text: 'Ciddi bir konuda gereksiz yere çok heyecanlan' },
  { id: 's34', text: 'Birine "dur bir saniye düşüneyim" deyip 3 sn sus' },
  { id: 's35', text: 'En az 2 kez "yok artık" veya "olmaz öyle şey" de' },
  { id: 's36', text: 'Birinin sözünü nazikçe kesip kendi hikayene geç' },
  { id: 's37', text: 'Birine "seni yanlış mı anladım?" diye sor (gerekmese bile)' },
  { id: 's38', text: 'Aynı cümleyi farklı kelimelerle bir kez daha söyle' },
  { id: 's39', text: 'Birine "bu çok derin bir konu" de (basit bir şey için)' },
  { id: 's40', text: 'En az bir kez "ben genelde böyle değilim ama..." de' },
  { id: 's41', text: 'Konuşurken ara sıra saçını veya kıyafetini düzelt' },
  { id: 's42', text: 'Dinlerken abartılı baş sallayarak onay ver' },
  { id: 's43', text: 'En az 2 kez içeceğine uzan / yudum al (yoksa taklit et)' },
  { id: 's44', text: 'Birine bir şey anlatırken el jestlerini abart' },
  { id: 's45', text: 'Konuşurken ara sıra arkana / odaya bak' },
  { id: 's46', text: 'Birine bir şey söylerken omzuna veya koluna hafifçe dokun' },
  { id: 's47', text: 'Telefonunu en az 2 kez kontrol ediyormuş gibi yap' },
  { id: 's48', text: 'Birine bakarken gülümse, başkasına bakarken ciddi kal' },
  { id: 's49', text: 'Masada en az 3 farklı kişiyi ismiyle an' },
  { id: 's50', text: 'Birine "seninle aynı fikirdeyim" de, sonra tam tersini savun' },
  { id: 's51', text: 'Bir hikayeyi anlatırken kahramanı kendin yap' },
  { id: 's52', text: 'Birine "bu arada süper duruyorsun bugün" de' },
  { id: 's53', text: 'En az 2 kez "doğru mu hatırlıyorum?" diye sor' },
  { id: 's54', text: 'Birine "sen olsan ne yapardın?" diye sor, cevabını abartıyla yorumla' },
  { id: 's55', text: 'Konuşmayı en az bir kez "asıl mesele şu ki..." diye yönlendir' },
  { id: 's56', text: 'Birine uydurma bir takma ad tak ve bir kez kullan' },
  { id: 's57', text: 'Birinin söylediğini "özetlersem..." diye yeniden formüle et' },
  { id: 's58', text: 'En az bir kez "bu gece unutulmaz olacak" tarzı abartılı cümle kur' },
]
